-- Generated by Envision Gui2Lua, VER-1, 0-18.

local Instances = {
	ScreenGui = Instance.new("ScreenGui"),
	Frame = Instance.new("Frame"),
	Frame_2 = Instance.new("Frame"),
	TextLabel = Instance.new("TextLabel"),
}

Instances.ScreenGui.Name = "ScreenGui"
Instances.ScreenGui.Parent = game.StarterGui

Instances.Frame.Name = "Frame"
Instances.Frame.Parent = Instances.ScreenGui
Instances.Frame.Size = UDim2.new(0, 234, 0, 6)
Instances.Frame.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.Frame.Position = UDim2.new(0.422121853, 0, 0, 0)
Instances.Frame.BorderSizePixel = 0
Instances.Frame.BackgroundColor3 = Color3.fromRGB(99, 109, 255)

Instances.Frame_2.Name = "Frame"
Instances.Frame_2.Parent = Instances.ScreenGui
Instances.Frame_2.Size = UDim2.new(0, 234, 0, 38)
Instances.Frame_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.Frame_2.Position = UDim2.new(0.422121853, 0, 0.00751879718, 0)
Instances.Frame_2.BorderSizePixel = 0
Instances.Frame_2.BackgroundColor3 = Color3.fromRGB(108, 108, 108)

Instances.TextLabel.Name = "TextLabel"
Instances.TextLabel.Parent = Instances.ScreenGui
Instances.TextLabel.Size = UDim2.new(0, 151, 0, 38)
Instances.TextLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextLabel.Position = UDim2.new(0.445750564, 0, 0.00751879718, 0)
Instances.TextLabel.BorderSizePixel = 0
Instances.TextLabel.BackgroundColor3 = Color3.fromRGB(108, 108, 108)
Instances.TextLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.TextLabel.Text = "oreol.xyz"
Instances.TextLabel.TextSize = 14
Instances.TextLabel.FontFace = Font.new("rbxasset://fonts/families/PressStart2P.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

--[[ End of generation. ]]
